spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

server:
  port: 8080

booking:
  platform:
    jwt:
      secret: ${JWT_SECRET}
    auth:
      bootstrap-default-merchant:
        enabled: ${BOOTSTRAP_DEFAULT_MERCHANT_ENABLED:false}
        name: ${BOOTSTRAP_DEFAULT_MERCHANT_NAME:}
        slug: ${BOOTSTRAP_DEFAULT_MERCHANT_SLUG:}
      bootstrap-default-merchant-user:
        enabled: ${BOOTSTRAP_DEFAULT_MERCHANT_USER_ENABLED:false}
        username: ${BOOTSTRAP_DEFAULT_MERCHANT_USER_USERNAME:}
        password: ${BOOTSTRAP_DEFAULT_MERCHANT_USER_PASSWORD:}
        merchant-slug: ${BOOTSTRAP_DEFAULT_MERCHANT_USER_MERCHANT_SLUG:}
      bootstrap-system-admin:
        enabled: ${BOOTSTRAP_SYSTEM_ADMIN_ENABLED:false}
        username: ${BOOTSTRAP_SYSTEM_ADMIN_USERNAME:}
        password: ${BOOTSTRAP_SYSTEM_ADMIN_PASSWORD:}
      bootstrap-default-client:
        enabled: ${BOOTSTRAP_DEFAULT_CLIENT_ENABLED:false}
        username: ${BOOTSTRAP_DEFAULT_CLIENT_USERNAME:}
        password: ${BOOTSTRAP_DEFAULT_CLIENT_PASSWORD:}

