spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

server:
  port: 8080

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

booking:
  platform:
    jwt:
      secret: ${JWT_SECRET}
    auth:
      internal-system-admin:
        auto-provision: ${INTERNAL_SYSTEM_ADMIN_AUTO_PROVISION:true}
        username: ${INTERNAL_SYSTEM_ADMIN_USERNAME:admin}
        password: ${INTERNAL_SYSTEM_ADMIN_PASSWORD:}

